# Generated by Django 2.2.10 on 2025-04-02 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20250327_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorevaluation',
            name='registration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.Register', verbose_name='挂号单'),
        ),
    ]
